### ISSUE TITLE
移动端不能进入编辑界面，在文件目录页面下点开任意一个文件就会显示页面错误

### ISSUE THREAD

**Issue by seasnakes** [zyascend/ZMindMap-Mobile#1]
![E1B7305E-1AB3-4158-A458-369B9D0D896D](https://user-images.githubusercontent.com/72481288/185055707-5a5b43b6-3f0f-49f7-886d-ea373021ac79.png)

**Comment by zyascend** [comment]
这部分功能还未实现，哈哈。
最近忙于秋招，没时间写了。等秋招结束会进行完整实现。感谢关注。

**Comment by seasnakes** [comment]
> 这部分功能还未实现，哈哈。 最近忙于秋招，没时间写了。等秋招结束会进行完整实现。感谢关注。

学长太强了吧，准大三的菜鸟给学长递烟😂。祝学长拿到心仪的offer，明年可以有机会去找你内推 哈哈哈 （暑假才开始自学vue，之前自己看过一点nodejs，参照着学长的项目学到了很多。现在仍在摸索研究中，希望开学之后能帮学长完善项目的文档说明啥的吧 respect🫡）
